### ISSUE TITLE
Internal Fields Are Accessible to User Programs

### ISSUE THREAD

**Issue by edgemaster** [resource-reasoning/JavaScriptVerification#3]
```javascript
var f = function() {};
__$ERROR__ = f["#class"];
```
Returns "Function"

This is probably a known issue, but introduces unsoundness?

**Comment by da319** [comment]
Yes, one way solve it would be to just reject programs that use internal
fields.

Daiva

**Comment by edgemaster** [comment]
Another way would be to prefix all user fields with some character. This may be the appropriate solution to implement attributes with also. (eg, `field` => `$value$field`, `$get$field`, `$enum$field` etc..)

**Comment by da319** [comment]
Fixed in [c6c1a7e](https://github.com/resource-reasoning/JavaScriptVerification/commit/c6c1a7e0722398bc4b2e5cdd015cb66345205e40)

**Comment by edgemaster** [comment]
Awesome!
